# Generated by Django 4.2.4 on 2023-08-14 08:05

from django.db import migrations, models
import django_ckeditor_5.fields
import django_cryptography.fields
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        ('core', '0029_agency_is_default_service_is_default'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agencytranslation',
            name='notes',
            field=django_cryptography.fields.encrypt(django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='description')),
        ),
        migrations.AlterField(
            model_name='template',
            name='service_option',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[(1, 'edu'), (2, 'travel'), (3, 'villa'), (4, 'corp')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='template',
            name='site',
            field=models.ManyToManyField(blank=True, related_name='templates_site', to='sites.site'),
        ),
    ]
