# Generated by Django 4.2.4 on 2023-08-16 19:52

from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_template_status_alter_service_kind_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuDefault',
            fields=[
                ('id', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('service_option', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[(1, 'E-Commerce'), (2, 'Agency'), (3, 'Saas'), (4, 'Business'), (5, 'Portofolio'), (6, 'Blog'), (9, 'Other')], max_length=255, null=True)),
                ('model_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.modellist')),
            ],
            options={
                'verbose_name': 'menu default',
                'verbose_name_plural': 'menus default',
                'unique_together': {('service_option', 'model_list')},
            },
        ),
    ]
