# Generated by Django 4.2 on 2023-10-09 15:48

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        ('core', '0034_globalsetting'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemplateBlock',
            fields=[
                ('id', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='block name')),
                ('variation', models.SmallIntegerField(default=1, verbose_name='variation number')),
                ('price_level', models.SmallIntegerField(default=1)),
                ('status', models.SmallIntegerField(choices=[(1, 'Draft'), (2, 'Published')], default=1)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sites.site')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.template')),
            ],
            options={
                'verbose_name': 'template block',
                'verbose_name_plural': 'template blocks',
            },
        ),
    ]
