# Generated by Django 4.2 on 2023-10-09 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_templateblock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='templateblock',
            name='site',
        ),
    ]
