# Generated by Django 4.2 on 2023-10-14 12:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_remove_templateblock_site'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='templateblock',
            name='variation',
        ),
        migrations.AddField(
            model_name='templateblock',
            name='model_list',
            field=models.ManyToManyField(blank=True, to='core.modellist'),
        ),
        migrations.AlterField(
            model_name='templateblock',
            name='name',
            field=models.CharField(default=None, max_length=100, verbose_name='block name'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='templateblock',
            name='price_level',
            field=models.SmallIntegerField(choices=[(1, 'Level 1'), (2, 'Level 2'), (3, 'Level 3'), (9, 'Custom Level')], default=1),
        ),
        migrations.AlterField(
            model_name='templateblock',
            name='template',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='core.template'),
        ),
    ]
