# Generated by Django 4.2 on 2023-10-19 11:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_alter_globalsetting_name_alter_globalsetting_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalsetting',
            name='ref_template_block',
            field=models.ForeignKey(default=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.templateblock'),
        ),
        migrations.AlterField(
            model_name='globalsetting',
            name='name',
            field=models.SmallIntegerField(choices=[(1, 'Slide Show'), (2, 'Menu')], default=None),
        ),
    ]
