# Generated by Django 4.2 on 2023-11-06 13:19

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0042_remove_templateblock_order_item_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgencyMeta',
            fields=[
                ('id', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('url', models.CharField(max_length=255, verbose_name='URL')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('description', models.CharField(max_length=500, verbose_name='description')),
                ('web_type', models.CharField(max_length=50, verbose_name='web type')),
                ('locale', models.CharField(max_length=10, verbose_name='locale')),
                ('locale_alternate', models.CharField(max_length=10, verbose_name='locale alternate')),
                ('image_type', models.CharField(max_length=50, verbose_name='image type')),
                ('agency', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.agency')),
            ],
            options={
                'verbose_name': 'agency meta',
                'verbose_name_plural': 'agency metas',
            },
        ),
    ]
