# Generated by Django 4.2 on 2023-11-06 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0043_agencymeta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agencymeta',
            name='image_type',
            field=models.SmallIntegerField(blank=True, choices=[(1, 'image/jpeg'), (2, 'image/png')], default=1, verbose_name='image type'),
        ),
        migrations.AlterField(
            model_name='agencymeta',
            name='locale',
            field=models.SmallIntegerField(blank=True, choices=[(1, 'id_ID'), (2, 'en_US')], default=1, verbose_name='locale'),
        ),
        migrations.AlterField(
            model_name='agencymeta',
            name='locale_alternate',
            field=models.SmallIntegerField(blank=True, choices=[(1, 'id_ID'), (2, 'en_US')], default=1, verbose_name='locale alternate'),
        ),
        migrations.AlterField(
            model_name='agencymeta',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='agencymeta',
            name='web_type',
            field=models.SmallIntegerField(blank=True, choices=[(1, 'website'), (2, 'article'), (3, 'profile'), (4, 'book'), (5, 'video'), (6, 'movie'), (7, 'education'), (8, 'news')], default=1, verbose_name='web type'),
        ),
    ]
