# Generated by Django 4.2 on 2024-11-01 11:21

from django.db import migrations
import django_ckeditor_5.fields
import django_cryptography.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0046_iconlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='agencytranslation',
            name='payment_notes',
            field=django_cryptography.fields.encrypt(django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='payment notes')),
        ),
    ]
