# Generated by Django 4.2.20 on 2025-05-31 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0047_agencytranslation_payment_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='description',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='photo description'),
        ),
    ]
