# Generated by Django 4.2.22 on 2025-06-26 12:51

from django.db import migrations, models
import django.db.models.deletion

def update_image_dimension(apps, schema_editor):    
    ImageDimension = apps.get_model('core', 'ImageDimension')
    ModelListSetting = apps.get_model('core', 'ModelListSetting')

    for i in ModelListSetting.objects.all():
        # for j in ImageDimension.objects.all():
        if (i.image_width > 0) or (i.image_height > 0):
            # position default
            ImageDimension.objects.create(
                model_list_setting_id=i.id,                
                image_width=i.image_width,
                image_height=i.image_height
            )

        # i.uuid = uuid.uuid4()
        # i.save(update_fields=['uuid'])


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0048_photo_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageDimension',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField(choices=[(0, 'Default'), (1, 'Top'), (2, 'Middle Top'), (3, 'Middle Bottom'), (4, 'Bottom')], default=0)),
                ('image_width', models.SmallIntegerField(default=0)),
                ('image_height', models.SmallIntegerField(default=0)),
                ('model_list_setting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.modellistsetting')),
            ],
        ),
        migrations.RunPython(update_image_dimension),
    ]
