# Generated by Django 4.2.22 on 2025-06-27 01:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0049_imagedimension'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modellistsetting',
            name='image_height',
        ),
        migrations.RemoveField(
            model_name='modellistsetting',
            name='image_width',
        ),
    ]
