# Generated by Django 4.2.30 on 2026-05-11 04:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0050_remove_modellistsetting_image_height_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='globalsetting',
            name='name',
            field=models.SmallIntegerField(choices=[(1, 'Slide Show'), (2, 'Menu'), (3, 'Why Us'), (4, 'Content Meta Info')], default=None),
        ),
        migrations.AlterField(
            model_name='globalsetting',
            name='ref_template_block',
            field=models.ForeignKey(blank=True, default=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.templateblock'),
        ),
        migrations.AlterField(
            model_name='imagedimension',
            name='position',
            field=models.PositiveIntegerField(choices=[(0, 'Default'), (1, 'Top'), (2, 'Middle Top'), (3, 'Middle Bottom'), (4, 'Bottom'), (5, 'Top Vertical')], default=0),
        ),
    ]
