# Generated by Django 4.2 on 2025-12-19 05:54

from django.db import migrations, models
import django.db.models.deletion
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('sites', '0002_alter_domain_unique'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('image', models.ImageField(upload_to='photos/%Y/%m/%d/', verbose_name='image')),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='title')),
                ('alt_text', models.CharField(blank=True, max_length=255, verbose_name='alt text')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'Photo',
                'verbose_name_plural': 'Photos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Code for AJAX identification', max_length=100, verbose_name='code')),
                ('value_type', models.SmallIntegerField(choices=[(1, 'Text'), (2, 'Image'), (3, 'Textarea'), (4, 'Icon'), (5, 'Unordered List'), (6, 'Navigation')], verbose_name='value type')),
                ('value_text', models.CharField(blank=True, max_length=255, null=True, verbose_name='text')),
                ('value_textarea', django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='value textarea')),
                ('template_id', models.CharField(blank=True, help_text='Template identifier', max_length=100, null=True, verbose_name='template ID')),
                ('order', models.IntegerField(default=0, verbose_name='order')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='api.content', verbose_name='parent')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sites.site', verbose_name='site')),
            ],
            options={
                'verbose_name': 'Content',
                'verbose_name_plural': 'Contents',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='content',
            index=models.Index(fields=['site', 'code'], name='api_content_site_id_9ce2ff_idx'),
        ),
        migrations.AddIndex(
            model_name='content',
            index=models.Index(fields=['parent'], name='api_content_parent__ad6609_idx'),
        ),
        migrations.AddIndex(
            model_name='content',
            index=models.Index(fields=['value_type'], name='api_content_value_t_309241_idx'),
        ),
    ]
