# Generated by Django 4.2.27 on 2025-12-22 07:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Unique template name', max_length=100, unique=True, verbose_name='template name')),
                ('description', models.TextField(blank=True, help_text='Template description', verbose_name='description')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
            ],
            options={
                'verbose_name': 'Template',
                'verbose_name_plural': 'Templates',
                'ordering': ['name'],
            },
        ),
        migrations.RemoveField(
            model_name='content',
            name='template_id',
        ),
        migrations.CreateModel(
            name='SiteMetadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_title', models.CharField(help_text='Main website title (shown in browser tab)', max_length=255, verbose_name='site title')),
                ('site_tagline', models.CharField(blank=True, help_text='Short tagline or slogan', max_length=255, verbose_name='site tagline')),
                ('meta_description', models.TextField(help_text='SEO meta description (recommended: 150-160 characters)', max_length=160, verbose_name='meta description')),
                ('meta_keywords', models.CharField(blank=True, help_text='Comma-separated keywords for SEO', max_length=255, verbose_name='meta keywords')),
                ('og_title', models.CharField(blank=True, help_text='Open Graph title (if different from site title)', max_length=255, verbose_name='og:title')),
                ('og_description', models.TextField(blank=True, help_text='Open Graph description', max_length=200, verbose_name='og:description')),
                ('og_image', models.ImageField(blank=True, help_text='Open Graph image (recommended: 1200x630px)', null=True, upload_to='og_images/%Y/%m/%d/', verbose_name='og:image')),
                ('og_type', models.CharField(default='website', help_text='Open Graph type (website, article, etc.)', max_length=50, verbose_name='og:type')),
                ('twitter_card', models.CharField(choices=[('summary', 'Summary'), ('summary_large_image', 'Summary Large Image'), ('app', 'App'), ('player', 'Player')], default='summary_large_image', help_text='Twitter card type', max_length=50, verbose_name='twitter:card')),
                ('twitter_site', models.CharField(blank=True, help_text='Twitter handle of website (e.g., @username)', max_length=100, verbose_name='twitter:site')),
                ('twitter_creator', models.CharField(blank=True, help_text='Twitter handle of content creator', max_length=100, verbose_name='twitter:creator')),
                ('favicon', models.ImageField(blank=True, help_text='Website favicon (.ico or .png, recommended: 32x32px)', null=True, upload_to='favicons/', verbose_name='favicon')),
                ('apple_touch_icon', models.ImageField(blank=True, help_text='Apple touch icon (recommended: 180x180px)', null=True, upload_to='icons/', verbose_name='apple touch icon')),
                ('logo', models.ImageField(blank=True, help_text='Website logo', null=True, upload_to='logos/', verbose_name='logo')),
                ('theme_color', models.CharField(default='#ffffff', help_text='Theme color for mobile browsers (hex color code)', max_length=7, verbose_name='theme color')),
                ('canonical_url', models.URLField(blank=True, help_text='Canonical URL for the site', verbose_name='canonical URL')),
                ('robots', models.CharField(default='index, follow', help_text='Robots meta tag content', max_length=100, verbose_name='robots')),
                ('google_site_verification', models.CharField(blank=True, help_text='Google Search Console verification code', max_length=100, verbose_name='google site verification')),
                ('google_analytics_id', models.CharField(blank=True, help_text='Google Analytics tracking ID (e.g., G-XXXXXXXXXX)', max_length=50, verbose_name='google analytics ID')),
                ('facebook_app_id', models.CharField(blank=True, help_text='Facebook App ID', max_length=50, verbose_name='facebook app ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('site', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='metadata', to='sites.site', verbose_name='site')),
            ],
            options={
                'verbose_name': 'Site Metadata',
                'verbose_name_plural': 'Site Metadata',
            },
        ),
        migrations.AddField(
            model_name='content',
            name='template',
            field=models.ForeignKey(blank=True, help_text='Template reference', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contents', to='api.template', verbose_name='template'),
        ),
    ]
