# Generated by Django 4.2 on 2026-01-17 09:59

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_userprofile_otp_otp_api_otp_user_id_47d984_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.ImageField(upload_to=api.models.site_image_path, verbose_name='image'),
        ),
    ]
