# Generated by Django 4.2 on 2026-01-17 10:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0004_alter_photo_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrustedDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_fingerprint', models.CharField(help_text='Unique device identifier (IP + User Agent hash)', max_length=255, verbose_name='device fingerprint')),
                ('trust_token', models.CharField(help_text='Token to identify this trusted device', max_length=64, unique=True, verbose_name='trust token')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('expires_at', models.DateTimeField(verbose_name='expires at')),
                ('last_used_at', models.DateTimeField(auto_now=True, verbose_name='last used at')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trusted_devices', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'Trusted Device',
                'verbose_name_plural': 'Trusted Devices',
            },
        ),
        migrations.AddIndex(
            model_name='trusteddevice',
            index=models.Index(fields=['user', 'device_fingerprint'], name='api_trusted_user_id_de75ea_idx'),
        ),
        migrations.AddIndex(
            model_name='trusteddevice',
            index=models.Index(fields=['trust_token'], name='api_trusted_trust_t_6bc162_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='trusteddevice',
            unique_together={('user', 'device_fingerprint')},
        ),
    ]
