# Generated by Django 4.2 on 2026-01-21 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_trusteddevice_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='content_type',
            field=models.SmallIntegerField(choices=[(1, 'Logo'), (2, 'Slideshow'), (3, 'Content'), (4, 'Navigation'), (5, 'Footer'), (6, 'Banner'), (99, 'Other')], default=99, help_text='Type of content (logo, slideshow, content, etc.)', verbose_name='content type'),
        ),
    ]
