# Generated by Django 4.2 on 2026-01-21 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_content_content_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='slug',
            field=models.SlugField(blank=True, help_text='SEO-friendly URL slug (auto-generated from title)', max_length=255, verbose_name='slug'),
        ),
        migrations.AddIndex(
            model_name='content',
            index=models.Index(fields=['site', 'slug'], name='api_content_site_id_321809_idx'),
        ),
    ]
