# Generated by Django 4.2 on 2026-01-23 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_content_slug_content_api_content_site_id_321809_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='value_video',
            field=models.URLField(blank=True, help_text='Video URL (YouTube, Vimeo, or direct video link)', max_length=500, null=True, verbose_name='video URL'),
        ),
    ]
