# Generated by Django 4.2 on 2026-02-07 14:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0008_content_value_video'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show_hero', models.BooleanField(default=True, help_text='Show or hide the hero section', verbose_name='show hero')),
                ('hero_text_alignment', models.CharField(choices=[('left', 'Left'), ('center', 'Center')], default='center', help_text='Hero text alignment', max_length=10, verbose_name='hero text alignment')),
                ('hero_button_label', models.CharField(default='Get Started', help_text='Custom label for hero CTA button', max_length=50, verbose_name='hero button label')),
                ('show_external_content', models.BooleanField(default=False, help_text='Show content from other sites', verbose_name='show external content')),
                ('breaking_news_animation', models.CharField(choices=[('typing', 'Typing Animation'), ('default', 'Default Animation')], default='default', help_text='Animation style for "Berita Terkini"', max_length=10, verbose_name='breaking news animation')),
                ('custom_favicon_url', models.URLField(blank=True, help_text='Custom favicon URL (overrides site default)', max_length=500, null=True, verbose_name='custom favicon URL')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'User Settings',
                'verbose_name_plural': 'User Settings',
            },
        ),
    ]
