# Generated by Django 4.2 on 2026-02-07 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_update_usersettings_to_key_value'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='usersettings',
            new_name='api_userset_user_id_08cb2f_idx',
            old_name='api_userSet_user_id_abc123_idx',
        ),
    ]
