# Generated by Django 4.2 on 2026-02-07 15:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_add_avatar_to_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='avatar',
            field=models.ForeignKey(blank=True, help_text='User profile avatar photo', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_avatars', to='api.photo', verbose_name='avatar'),
        ),
    ]
