# Generated by Django 4.2 on 2026-02-09 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_add_avatar_field_to_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='url',
            field=models.CharField(blank=True, help_text='Custom URL for navigation menu items', max_length=500, null=True, verbose_name='url'),
        ),
        migrations.AlterField(
            model_name='content',
            name='content_type',
            field=models.SmallIntegerField(choices=[(1, 'Logo'), (2, 'Slideshow'), (3, 'Content'), (4, 'Navigation'), (5, 'Footer'), (6, 'Banner'), (7, 'Avatar'), (8, 'Favicon'), (99, 'Other')], default=99, help_text='Type of content (logo, slideshow, content, etc.)', verbose_name='content type'),
        ),
        migrations.AlterField(
            model_name='content',
            name='value_type',
            field=models.SmallIntegerField(choices=[(1, 'Text-Only'), (2, 'Text-Image'), (3, 'Text-Video')], verbose_name='value type'),
        ),
    ]
