# Generated by Django 4.2.27 on 2026-02-10 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_content_url_alter_content_content_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='is_page',
            field=models.BooleanField(default=False, help_text='Mark this content as a page (vs regular content/article)', verbose_name='is page'),
        ),
        migrations.AlterField(
            model_name='content',
            name='content_type',
            field=models.SmallIntegerField(choices=[(1, 'Logo'), (2, 'Slideshow'), (3, 'Content'), (4, 'Navigation'), (5, 'Footer'), (6, 'Banner'), (7, 'Avatar'), (8, 'Favicon'), (9, 'Pages'), (99, 'Other')], default=99, help_text='Type of content (logo, slideshow, content, etc.)', verbose_name='content type'),
        ),
    ]
