_AR='MAIN_DOMAIN'
_AQ='ck-heading_heading3'
_AP='Heading 3'
_AO='ck-heading_heading2'
_AN='Heading 2'
_AM='ck-heading_heading1'
_AL='Heading 1'
_AK='ck-heading_paragraph'
_AJ='Paragraph'
_AI='mergeTableCells'
_AH='tableColumn'
_AG='contentToolbar'
_AF='insertTable'
_AE='removeFormat'
_AD='fontBackgroundColor'
_AC='fontColor'
_AB='fontFamily'
_AA='sourceEditing'
_A9='codeBlock'
_A8='highlight'
_A7='superscript'
_A6='subscript'
_A5='strikethrough'
_A4='underline'
_A3='alignment'
_A2='extraProviders'
_A1='previewsInData'
_A0='blockToolbar'
_z='authbox.web.id'
_y='smtp.gmail.com'
_x='MEDIA_ROOT'
_w='STATIC_ROOT'
_v='templates'
_u='127.0.0.1'
_t='PASSWORD'
_s='DB_NAME'
_r='OPTIONS'
_q='allauth'
_p='ALLOWED_HOSTS'
_o='SECRET_KEY'
_n='DB_PASSWORD'
_m='key'
_l='secret'
_k='client_id'
_j='APP'
_i='link'
_h='italic'
_g='bold'
_f='/dashboard/'
_e='environment'
_d='backgroundColors'
_c='borderColors'
_b='tableCellProperties'
_a='tableProperties'
_Z='heading3'
_Y='heading2'
_X='heading1'
_W='paragraph'
_V='mediaEmbed'
_U='toolbar'
_T='code'
_S='ENGINE'
_R='DIRS'
_Q='true'
_P='blockQuote'
_O='numberedList'
_N='bulletedList'
_M='heading'
_L='id'
_K='view'
_J='label'
_I='color'
_H=False
_G='default'
_F='class'
_E='title'
_D='model'
_C='NAME'
_B=True
_A='|'
import logging,os
from pathlib import Path
from decouple import config,Csv
from django.utils.translation import gettext_lazy as _
from encryption import OutboxEncryption
logger=logging.getLogger(__name__)
BASE_DIR=Path(__file__).resolve().parent.parent
BASE_DIR_1=os.path.normpath(os.path.join(BASE_DIR,'..'))
BASE_DIR_2=os.path.normpath(os.path.join(BASE_DIR_1,'..'))
AES_KEY='ad6a17d79291b2143a34f1859784e6380b77faddd4abbf928dddb5bdc070908f'
LIB=OutboxEncryption(os.path.join(BASE_DIR,_e))
file_name=LIB.scan_environment_variable()
file_name_color='\x1b[91m'+file_name+'\x1b[0m'
file_path=os.path.join(BASE_DIR,_e,file_name)
file_path_color=os.path.join(BASE_DIR,_e,file_name_color)
if not Path(file_path).is_file():raise Exception(f"[1m File Not found: [0m {file_path_color}")
PLAINT_KEY=[_n,_o]
PLAINT_LIST=[_p]
KEY=LIB.dec_environ(PLAINT_KEY,PLAINT_LIST)
DEBUG=KEY['DEBUG']
UNDER_CONSTRUCTION=KEY['UNDER_CONSTRUCTION']
SECRET_KEY=KEY[_o]
ALLOWED_HOSTS=KEY[_p]
CSRF_TRUSTED_ORIGINS=['http://localhost:5173','http://127.0.0.1:5173']
ROOT_URLCONF='django_authbox.urls'
INSTALLED_APPS=['django.contrib.admin','django.contrib.auth','django.contrib.contenttypes','django.contrib.sessions','django.contrib.messages','django.contrib.staticfiles','rest_framework','django.contrib.sites','django.contrib.humanize',_q,'allauth.account','allauth.socialaccount','allauth.socialaccount.providers.google','allauth.socialaccount.providers.facebook','allauth.socialaccount.providers.github','django_recaptcha','multiselectfield','parler','crispy_forms','crispy_bootstrap4','django_ckeditor_5','corsheaders','mobiledetect','djmoney','django_social_share','menu','region','outbox_hitcount','hitcount','core','backend','frontend','api','docs','django_filters','captcha']
MIDDLEWARE=['django.middleware.security.SecurityMiddleware','django.contrib.sessions.middleware.SessionMiddleware','core.force_default_language_middleware.ForceDefaultLanguageMiddleware','django.middleware.locale.LocaleMiddleware','corsheaders.middleware.CorsMiddleware','django.middleware.common.CommonMiddleware','django.middleware.csrf.CsrfViewMiddleware','django.contrib.auth.middleware.AuthenticationMiddleware','django.contrib.messages.middleware.MessageMiddleware','django.middleware.clickjacking.XFrameOptionsMiddleware','mobiledetect.middleware.DetectMiddleware','allauth.account.middleware.AccountMiddleware']
TEMPLATES=[{'BACKEND':'django.template.backends.django.DjangoTemplates',_R:[],'APP_DIRS':_B,_r:{'context_processors':['django.template.context_processors.debug','django.template.context_processors.request','django.contrib.auth.context_processors.auth','django.contrib.messages.context_processors.messages','frontend.processor.context_outbox','backend.processor.context_outbox','backend.processor.get_main_domain','backend.processor.site_id','backend.processor.version','core.processor.get_static_version']}}]
WSGI_APPLICATION='django_authbox.wsgi.application'
DB_ENGINE=KEY['DB_ENGINE']
if'sqlite3'in DB_ENGINE:
	db_name=KEY[_s]
	if db_name.find('/')<0 and db_name.find('\\')<0:DATABASES={_G:{_S:DB_ENGINE,_C:os.path.join(BASE_DIR,'db',db_name)}}
	else:DATABASES={_G:{_S:DB_ENGINE,_C:db_name}}
else:DATABASES={_G:{_S:DB_ENGINE,_C:KEY[_s],'USER':KEY['DB_USER'],_t:KEY[_n],'HOST':KEY['DB_HOST'],'PORT':KEY['DB_PORT']}}
DATABASES.update({'second_db':{_S:'django.db.backends.mysql',_C:'db_lobar_restore','USER':'root',_t:'','HOST':_u,'PORT':'3306'}})
tmp=os.path.basename(DATABASES[_G][_C])
logger.error(f"Database Name[94m {tmp}[0m")
AUTH_PASSWORD_VALIDATORS=[{_C:'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},{_C:'django.contrib.auth.password_validation.MinimumLengthValidator'},{_C:'django.contrib.auth.password_validation.CommonPasswordValidator'},{_C:'django.contrib.auth.password_validation.NumericPasswordValidator'}]
LANGUAGE_CODE=_L
TIME_ZONE='Asia/Makassar'
USE_I18N=_B
USE_L10N=_B
USE_TZ=_B
STATIC_URL='/static/'
DEFAULT_AUTO_FIELD='django.db.models.BigAutoField'
SITE_ID=1
CONTRIBUTE_PATH=os.path.join(BASE_DIR_2,'authbox-contribute','clothes')
TEMPLATES[0][_R].clear()
TEMPLATES[0][_R].append(os.path.join(CONTRIBUTE_PATH,_v))
TEMPLATES[0][_R].append(os.path.join(CONTRIBUTE_PATH,_v,_q))
STATIC_ROOT=KEY[_w]if KEY.get(_w)else os.path.join(CONTRIBUTE_PATH,'staticfiles')
path_level_up=os.path.abspath(os.path.join(STATIC_ROOT,'..','staticserver'))
STATICFILES_DIRS=[path_level_up]
MEDIA_URL='/media/'
MEDIA_ROOT=KEY[_x]if KEY.get(_x)else os.path.join(CONTRIBUTE_PATH,'media')
MIDDLEWARE+=['frontend.request_exposer.RequestExposerMiddleware','core.request_exposer.RequestExposerMiddleware']
HITCOUNT_KEEP_HIT_IN_DATABASE={'days':60}
HITCOUNT_KEEP_HIT_ACTIVE={'minutes':10}
LANGUAGES=(_L,_('Indonesia')),('en',_('English'))
LOCALE_PATHS=[os.path.join(BASE_DIR,'locale')]
PARLER_DEFAULT_LANGUAGE_CODE=_L
PARLER_LANGUAGES={1:({_T:_L},{_T:'en'}),_G:{'fallbacks':[_L],'hide_untranslated':_H}}
RECAPTCHA_PUBLIC_KEY='6Le_ixcmAAAAABbCXol2K5HaE0vY906KKFrFm0PX'
RECAPTCHA_PRIVATE_KEY='6Le_ixcmAAAAAFeqpjBlKQcgDkPxZjMmk--cuEZU'
IMPORT_EXPORT_USE_TRANSACTIONS=_B
LOGIN_REDIRECT_URL=_f
LOGOUT_REDIRECT_URL=_f
AUTH_USER_MODEL='core.User'
ACCOUNT_FORMS={'login':'core.forms.UserLoginForm','reset_password':'core.forms.UserResetPasswordForm','signup':'core.forms.UserSignupForm'}
AUTHENTICATION_BACKENDS=['allauth.account.auth_backends.AuthenticationBackend']
EMAIL_USE_SSL=_H
EMAIL_BACKEND='django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST=_y
EMAIL_HOST_USER='auto.email.activation@gmail.com'
EMAIL_HOST_PASSWORD='hpsodjhhkhaemoir'
EMAIL_PORT=587
EMAIL_USE_TLS=_B
DEFAULT_FROM_EMAIL='AUTHBOX.web.id'
ACCOUNT_AUTHENTICATED_LOGIN_REDIRECTS=_H
ACCOUNT_LOGIN_ON_PASSWORD_RESET=_B
ACCOUNT_LOGOUT_ON_PASSWORD_CHANGE=_B
ACCOUNT_USERNAME_MIN_LENGTH=4
ACCOUNT_SESSION_REMEMBER=_B
ACCOUNT_EMAIL_CONFIRMATION_EXPIRE_DAYS=1
ACCOUNT_SIGNUP_FIELDS=['email*','password1*','password2*']
ACCOUNT_RATE_LIMITS=_H
ACCOUNT_LOGOUT_REDIRECT_URL=_f
ACCOUNT_LOGIN_REDIRECT_URL='/id/dashboard/'
ACCOUNT_LOGIN_METHODS={'email'}
ACCOUNT_UNIQUE_EMAIL=_B
ACCOUNT_USER_MODEL_USERNAME_FIELD=None
ACCOUNT_LOGOUT_ON_GET=_B
SOCIALACCOUNT_LOGIN_ON_GET=_H
SENDGRID_API_KEY='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'
INTERNAL_IPS=[_u,'localhost',_z]
customColorPalette=[{_I:'hsl(4, 90%, 58%)',_J:'Red'},{_I:'hsl(340, 82%, 52%)',_J:'Pink'},{_I:'hsl(291, 64%, 42%)',_J:'Purple'},{_I:'hsl(262, 52%, 47%)',_J:'Deep Purple'},{_I:'hsl(231, 48%, 48%)',_J:'Indigo'},{_I:'hsl(207, 90%, 54%)',_J:'Blue'}]
CKEDITOR_5_CONFIGS={_G:{_U:[_M,_A,_g,_h,_i,_N,_O,_P,'imageUpload']},'extends':{_A0:[_W,_X,_Y,_Z,_A,_N,_O,_A,_P],_V:{_A1:_Q,_A2:[{'name':'all','url':'/^.+/'}]},_U:[_M,_A,'outdent','indent',_A,_A3,_A,_g,_h,_A4,_A5,_A,_i,_A,_T,_A6,_A7,_A8,_A,_N,_O,'todoList',_A,_A9,_V,'insertImage',_AA,_A,_P,_A,_AB,'fontSize',_AC,_AD,_AE,_AF],'image':{_U:['imageTextAlternative',_A,'imageStyle:alignLeft','imageStyle:alignRight','imageStyle:alignCenter','imageStyle:side',_A],'styles':['full','side','alignLeft','alignRight','alignCenter']},'table':{_AG:[_AH,'tableRow',_AI,_a,_b],_a:{_c:customColorPalette,_d:customColorPalette},_b:{_c:customColorPalette,_d:customColorPalette}},_M:{'options':[{_D:_W,_E:_AJ,_F:_AK},{_D:_X,_K:'h1',_E:_AL,_F:_AM},{_D:_Y,_K:'h2',_E:_AN,_F:_AO},{_D:_Z,_K:'h3',_E:_AP,_F:_AQ}]}},'extends_noimage':{_A0:[_W,_X,_Y,_Z,_A,_N,_O,_A,_P],_V:{_A1:_Q,_A2:[{'name':'all','url':'/^.+/'}]},_U:[_M,_A,'outdent','indent',_A,_A3,_A,_g,_h,_A4,_A5,_A,_i,_A,_T,_A6,_A7,_A8,_A,_N,_O,'todoList',_A,_A9,_V,_AA,_A,_P,_A,_AB,'fontSize',_AC,_AD,_AE,_AF],'table':{_AG:[_AH,'tableRow',_AI,_a,_b],_a:{_c:customColorPalette,_d:customColorPalette},_b:{_c:customColorPalette,_d:customColorPalette}},_M:{'options':[{_D:_W,_E:_AJ,_F:_AK},{_D:_X,_K:'h1',_E:_AL,_F:_AM},{_D:_Y,_K:'h2',_E:_AN,_F:_AO},{_D:_Z,_K:'h3',_E:_AP,_F:_AQ}]}},'list':{'properties':{'styles':_Q,'startIndex':_Q,'reversed':_Q}}}
CRISPY_TEMPLATE_PACK='bootstrap4'
tmp=KEY.get(_AR)
MAIN_DOMAIN=KEY[_AR]if tmp else'localhost:8000'
SOCIALACCOUNT_PROVIDERS={'github':{_j:{_k:'6c0e925336cace458a21',_l:'e5e0a76006524a3b49e9c0593ac29f2d1ee8c354',_m:''}},'facebook':{_j:{_k:'1582129178867576',_l:'6edc1f622ef5ba62ec8d8e54d8228ef8',_m:''}},'google':{_j:{_k:'921195599940-a4ft11sk9m64oop9vr1amjkvu8g192af.apps.googleusercontent.com',_l:'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',_m:''},'SCOPE':['profile','email'],'AUTH_PARAMS':{'access_type':'online'}}}
CPANEL_USER='u1578244'
CPANEL_TOKEN='QQ0GWU5HOJ7OYZWNM82IX2IA6PZGEK6M'
CPANEL_URL='srv135.niagahoster.com'
CPANEL_DOMAIN=_z
DOCS_ROOT=os.path.join(BASE_DIR,'docs/_build/html')
DOCS_ACCESS='public'
CKEDITOR_5_FILE_UPLOAD_PERMISSION='staff'
CKEDITOR_5_ALLOW_ALL_FILE_TYPES=_B
CKEDITOR_5_UPLOAD_FILE_TYPES=['jpeg','pdf','png']
CKEDITOR_5_MAX_FILE_SIZE=1
CORS_ALLOWED_ORIGINS=['http://localhost:8000','http://127.0.0.1:8000']
STATICFILES_FINDERS=['django.contrib.staticfiles.finders.FileSystemFinder','django.contrib.staticfiles.finders.AppDirectoriesFinder']
REST_FRAMEWORK={'DEFAULT_PAGINATION_CLASS':'rest_framework.pagination.PageNumberPagination','PAGE_SIZE':10,'DEFAULT_FILTER_BACKENDS':['django_filters.rest_framework.DjangoFilterBackend','rest_framework.filters.SearchFilter','rest_framework.filters.OrderingFilter'],'DEFAULT_RENDERER_CLASSES':['rest_framework.renderers.JSONRenderer','rest_framework.renderers.BrowsableAPIRenderer'],'DEFAULT_PARSER_CLASSES':['rest_framework.parsers.JSONParser','rest_framework.parsers.MultiPartParser','rest_framework.parsers.FormParser'],'DEFAULT_AUTHENTICATION_CLASSES':['rest_framework.authentication.SessionAuthentication']}
SESSION_COOKIE_SAMESITE='Lax'
SESSION_COOKIE_HTTPONLY=_B
SESSION_COOKIE_SECURE=config('SESSION_COOKIE_SECURE',default=_H,cast=bool)
SESSION_COOKIE_AGE=86400
EMAIL_BACKEND=config('EMAIL_BACKEND',default='django.core.mail.backends.console.EmailBackend')
EMAIL_HOST=config('EMAIL_HOST',default=_y)
EMAIL_PORT=config('EMAIL_PORT',default=587,cast=int)
EMAIL_USE_TLS=config('EMAIL_USE_TLS',default=_B,cast=bool)
EMAIL_HOST_USER=config('EMAIL_HOST_USER',default='')
EMAIL_HOST_PASSWORD=config('EMAIL_HOST_PASSWORD',default='')
DEFAULT_FROM_EMAIL=config('DEFAULT_FROM_EMAIL',default='noreply@example.com')
CAPTCHA_IMAGE_SIZE=150,50
CAPTCHA_FONT_SIZE=30
CAPTCHA_LENGTH=6
CAPTCHA_TIMEOUT=5
CAPTCHA_CHALLENGE_FUNCT='captcha.helpers.random_char_challenge'
OTP_EXPIRATION_MINUTES=10
CORS_ALLOWED_ORIGINS=config('CORS_ALLOWED_ORIGINS',default='http://localhost:5173,http://127.0.0.1:5173,http://localhost:5174,http://127.0.0.1:5174,http://test.authbox.web.id:5174,https://test.authbox.web.id',cast=Csv())
CORS_ALLOW_CREDENTIALS=_B
CORS_ALLOW_METHODS=['DELETE','GET',_r,'PATCH','POST','PUT']
CORS_ALLOW_HEADERS=['accept','accept-encoding','authorization','content-type','dnt','origin','user-agent','x-csrftoken','x-requested-with']
STATIC_VERSION='20250718'