# Generated by Django 4.2.4 on 2023-08-10 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0027_product_icon_alter_aboutustranslation_sub_title'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='heroimagetranslation',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='heroimagetranslation',
            name='master',
        ),
        migrations.DeleteModel(
            name='HeroImage',
        ),
        migrations.DeleteModel(
            name='HeroImageTranslation',
        ),
    ]
