# Generated by Django 4.2.4 on 2023-08-10 14:45

from django.db import migrations
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0029_alter_aboutustranslation_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='slideshow',
            name='text',
            field=django_ckeditor_5.fields.CKEditor5Field(default=None, verbose_name='Text'),
            preserve_default=False,
        ),
    ]
