# Generated by Django 4.2.4 on 2023-08-24 12:00

from django.db import migrations, models
import django_cryptography.fields


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0031_remove_testimony_come_from_remove_testimony_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='is_header_text',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='locationtranslation',
            name='subtitle',
            field=django_cryptography.fields.encrypt(models.CharField(default=None, max_length=500, verbose_name='subtitle')),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='locationtranslation',
            name='title',
            field=django_cryptography.fields.encrypt(models.CharField(max_length=100, verbose_name='title')),
        ),
    ]
