# Generated by Django 4.2.4 on 2023-08-31 17:59

from django.db import migrations, models
import django_cryptography.fields


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0034_document_share_count_document_slug_document_tags_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='is_header_text',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='announcementtranslation',
            name='sub_title',
            field=django_cryptography.fields.encrypt(models.CharField(blank=True, max_length=500, null=True, verbose_name='sub title')),
        ),
        migrations.AddField(
            model_name='articletranslation',
            name='sub_title',
            field=django_cryptography.fields.encrypt(models.CharField(blank=True, max_length=500, null=True, verbose_name='sub title')),
        ),
        migrations.AddField(
            model_name='document',
            name='is_header_text',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='events',
            name='is_header_text',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='eventstranslation',
            name='sub_title',
            field=django_cryptography.fields.encrypt(models.CharField(blank=True, max_length=500, null=True, verbose_name='sub title')),
        ),
        migrations.AddField(
            model_name='news',
            name='is_header_text',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='newstranslation',
            name='sub_title',
            field=django_cryptography.fields.encrypt(models.CharField(blank=True, max_length=500, null=True, verbose_name='sub title')),
        ),
        migrations.AddField(
            model_name='pages',
            name='is_header_text',
            field=models.BooleanField(default=False),
        ),
    ]
