# Generated by Django 4.2.4 on 2023-08-31 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0035_announcement_is_header_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='whyus',
            name='is_header_text',
            field=models.BooleanField(default=False),
        ),
    ]
