# Generated by Django 4.2.4 on 2023-09-02 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0036_whyus_is_header_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutus',
            name='is_header_text',
            field=models.BooleanField(default=False),
        ),
    ]
