# Generated by Django 4.2.4 on 2023-09-08 10:38

from django.db import migrations, models
import django_cryptography.fields


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0037_aboutus_is_header_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='fasilitiestranslation',
            name='sub_title',
            field=django_cryptography.fields.encrypt(models.CharField(blank=True, max_length=500, null=True, verbose_name='sub title')),
        ),
        migrations.AddField(
            model_name='howitworkstranslation',
            name='sub_title',
            field=django_cryptography.fields.encrypt(models.CharField(blank=True, max_length=500, null=True, verbose_name='sub title')),
        ),
        migrations.AddField(
            model_name='offerstranslation',
            name='sub_title',
            field=django_cryptography.fields.encrypt(models.CharField(blank=True, max_length=500, null=True, verbose_name='sub title')),
        ),
        migrations.AddField(
            model_name='whyustranslation',
            name='sub_title',
            field=django_cryptography.fields.encrypt(models.CharField(blank=True, max_length=500, null=True, verbose_name='sub title')),
        ),
        migrations.AlterField(
            model_name='howitworkstranslation',
            name='content',
            field=django_cryptography.fields.encrypt(models.CharField(blank=True, max_length=500, null=True, verbose_name='content')),
        ),
    ]
