# Generated by Django 4.2.4 on 2023-09-08 14:02

from django.db import migrations, models
import django_cryptography.fields


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0038_fasilitiestranslation_sub_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producttranslation',
            name='sub_title',
            field=django_cryptography.fields.encrypt(models.CharField(blank=True, max_length=500, null=True, verbose_name='sub title')),
        ),
    ]
