# Generated by Django 4.2 on 2023-09-17 12:14

from django.db import migrations, models
import django_cryptography.fields


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0041_aboutus_is_initial_data_announcement_is_initial_data_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutustranslation',
            name='sub_title',
            field=django_cryptography.fields.encrypt(models.CharField(max_length=300, verbose_name='sub title')),
        ),
        migrations.AlterField(
            model_name='aboutustranslation',
            name='title',
            field=django_cryptography.fields.encrypt(models.CharField(max_length=300, verbose_name='title')),
        ),
        migrations.AlterField(
            model_name='announcementtranslation',
            name='sub_title',
            field=django_cryptography.fields.encrypt(models.CharField(blank=True, max_length=300, null=True, verbose_name='sub title')),
        ),
        migrations.AlterField(
            model_name='announcementtranslation',
            name='title',
            field=django_cryptography.fields.encrypt(models.CharField(max_length=300, verbose_name='title')),
        ),
        migrations.AlterField(
            model_name='articletranslation',
            name='sub_title',
            field=django_cryptography.fields.encrypt(models.CharField(blank=True, max_length=300, null=True, verbose_name='sub title')),
        ),
        migrations.AlterField(
            model_name='articletranslation',
            name='title',
            field=django_cryptography.fields.encrypt(models.CharField(max_length=300, verbose_name='title')),
        ),
        migrations.AlterField(
            model_name='categories',
            name='slug',
            field=models.SlugField(blank=True, default='', editable=False, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='categoriestranslation',
            name='name',
            field=models.CharField(max_length=100, verbose_name='categories name'),
        ),
        migrations.AlterField(
            model_name='documenttranslation',
            name='name',
            field=django_cryptography.fields.encrypt(models.CharField(max_length=100, verbose_name='name')),
        ),
        migrations.AlterField(
            model_name='eventstranslation',
            name='sub_title',
            field=django_cryptography.fields.encrypt(models.CharField(blank=True, max_length=300, null=True, verbose_name='sub title')),
        ),
        migrations.AlterField(
            model_name='eventstranslation',
            name='title',
            field=django_cryptography.fields.encrypt(models.CharField(max_length=300, verbose_name='title')),
        ),
        migrations.AlterField(
            model_name='fasilitiestranslation',
            name='sub_title',
            field=django_cryptography.fields.encrypt(models.CharField(blank=True, max_length=300, null=True, verbose_name='sub title')),
        ),
        migrations.AlterField(
            model_name='fasilitiestranslation',
            name='title',
            field=django_cryptography.fields.encrypt(models.CharField(max_length=300, verbose_name='title')),
        ),
        migrations.AlterField(
            model_name='greetingtranslation',
            name='designation',
            field=django_cryptography.fields.encrypt(models.CharField(blank=True, max_length=100, null=True, verbose_name='designation')),
        ),
        migrations.AlterField(
            model_name='greetingtranslation',
            name='name',
            field=django_cryptography.fields.encrypt(models.CharField(blank=True, max_length=100, null=True, verbose_name='greeting name')),
        ),
        migrations.AlterField(
            model_name='greetingtranslation',
            name='title',
            field=models.CharField(max_length=300, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='howitworkstranslation',
            name='sub_title',
            field=django_cryptography.fields.encrypt(models.CharField(blank=True, max_length=300, null=True, verbose_name='sub title')),
        ),
        migrations.AlterField(
            model_name='howitworkstranslation',
            name='title',
            field=django_cryptography.fields.encrypt(models.CharField(max_length=300, verbose_name='title')),
        ),
        migrations.AlterField(
            model_name='locationtranslation',
            name='subtitle',
            field=django_cryptography.fields.encrypt(models.CharField(max_length=300, verbose_name='subtitle')),
        ),
        migrations.AlterField(
            model_name='locationtranslation',
            name='title',
            field=django_cryptography.fields.encrypt(models.CharField(max_length=300, verbose_name='title')),
        ),
        migrations.AlterField(
            model_name='newstranslation',
            name='sub_title',
            field=django_cryptography.fields.encrypt(models.CharField(blank=True, max_length=300, null=True, verbose_name='sub title')),
        ),
        migrations.AlterField(
            model_name='newstranslation',
            name='title',
            field=django_cryptography.fields.encrypt(models.CharField(max_length=300, verbose_name='title')),
        ),
        migrations.AlterField(
            model_name='offerstranslation',
            name='sub_title',
            field=django_cryptography.fields.encrypt(models.CharField(blank=True, max_length=300, null=True, verbose_name='sub title')),
        ),
        migrations.AlterField(
            model_name='offerstranslation',
            name='title',
            field=django_cryptography.fields.encrypt(models.CharField(max_length=300, verbose_name='title')),
        ),
        migrations.AlterField(
            model_name='pagestranslation',
            name='sub_title',
            field=django_cryptography.fields.encrypt(models.CharField(blank=True, max_length=300, null=True, verbose_name='sub title')),
        ),
        migrations.AlterField(
            model_name='pagestranslation',
            name='title',
            field=django_cryptography.fields.encrypt(models.CharField(max_length=300, verbose_name='title')),
        ),
        migrations.AlterField(
            model_name='photogallerytranslation',
            name='title',
            field=django_cryptography.fields.encrypt(models.CharField(max_length=300, verbose_name='title')),
        ),
        migrations.AlterField(
            model_name='popuptranslation',
            name='title',
            field=django_cryptography.fields.encrypt(models.CharField(max_length=300, verbose_name='title')),
        ),
        migrations.AlterField(
            model_name='producttranslation',
            name='sub_title',
            field=django_cryptography.fields.encrypt(models.CharField(blank=True, max_length=300, null=True, verbose_name='sub title')),
        ),
        migrations.AlterField(
            model_name='producttranslation',
            name='title',
            field=django_cryptography.fields.encrypt(models.CharField(max_length=300, verbose_name='title')),
        ),
        migrations.AlterField(
            model_name='relatedlinktranslation',
            name='name',
            field=django_cryptography.fields.encrypt(models.CharField(max_length=100, verbose_name='name')),
        ),
        migrations.AlterField(
            model_name='slideshowtranslation',
            name='sub_title',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='sub title'),
        ),
        migrations.AlterField(
            model_name='slideshowtranslation',
            name='title',
            field=models.CharField(max_length=300, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='tags',
            name='slug',
            field=models.SlugField(blank=True, default='', editable=False, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='tagstranslation',
            name='name',
            field=models.CharField(max_length=100, verbose_name='tags name'),
        ),
        migrations.AlterField(
            model_name='testimony',
            name='subtitle',
            field=django_cryptography.fields.encrypt(models.CharField(max_length=300, verbose_name='subtitle')),
        ),
        migrations.AlterField(
            model_name='testimony',
            name='title',
            field=django_cryptography.fields.encrypt(models.CharField(max_length=300, verbose_name='title')),
        ),
        migrations.AlterField(
            model_name='videogallerytranslation',
            name='title',
            field=django_cryptography.fields.encrypt(models.CharField(max_length=300, verbose_name='title')),
        ),
        migrations.AlterField(
            model_name='whyustranslation',
            name='sub_title',
            field=django_cryptography.fields.encrypt(models.CharField(blank=True, max_length=300, null=True, verbose_name='sub title')),
        ),
        migrations.AlterField(
            model_name='whyustranslation',
            name='title',
            field=models.CharField(max_length=300, verbose_name='title'),
        ),
    ]
