# Generated by Django 4.2 on 2023-09-17 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0042_alter_aboutustranslation_sub_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='videogallery',
            name='is_header_text',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='videogallery',
            name='order_item',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
