# Generated by Django 4.2 on 2023-10-07 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0043_videogallery_is_header_text_videogallery_order_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='file_path_doc',
            field=models.FileField(upload_to='temp_doc', verbose_name='file path Document'),
        ),
    ]
