# Generated by Django 4.2 on 2024-01-28 10:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0046_iconlist'),
        ('frontend', '0044_alter_document_file_path_doc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutus',
            name='is_header_text',
        ),
        migrations.AddField(
            model_name='aboutus',
            name='detail_post',
            field=models.SmallIntegerField(choices=[(1, 'Title'), (2, 'Narration'), (3, 'Image'), (4, 'List')], default=1),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='icon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.iconlist'),
        ),
    ]
