# Generated by Django 4.2 on 2024-01-29 04:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0045_remove_aboutus_is_header_text_aboutus_detail_post_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutus',
            name='detail_post',
        ),
        migrations.RemoveField(
            model_name='aboutus',
            name='icon',
        ),
    ]
