# Generated by Django 4.2 on 2024-08-15 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0047_googlecalendardetail_description_and_more'),
    ]


    operations = [
        migrations.RenameField(
            model_name='googlecalendar',
            old_name='cal_name',
            new_name='calendar_id',
        ),
        migrations.AlterField(
            model_name='googlecalendardetail',
            name='description',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='googlecalendardetail',
            name='end',
            field=models.DateTimeField(blank=True, null=True, verbose_name='date end'),
        ),
        migrations.AlterField(
            model_name='googlecalendardetail',
            name='location',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='location'),
        ),
        migrations.AlterField(
            model_name='googlecalendardetail',
            name='start',
            field=models.DateTimeField(blank=True, null=True, verbose_name='date start'),
        ),
        migrations.AlterField(
            model_name='googlecalendardetail',
            name='summary',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Summary'),
        ),
        migrations.AlterField(
            model_name='googlecalendardetail',
            name='transparency',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='transparency'),
        ),
        migrations.AlterField(
            model_name='googlecalendardetail',
            name='visibility',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='visibility'),
        ),
    ]
