# Generated by Django 4.2 on 2024-08-19 03:47

from django.db import migrations, models
import django.db.models.deletion
import frontend.models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        ('frontend', '0048_rename_cal_name_googlecalendar_calendar_id_and_more'),
    ]


    operations = [
        migrations.AlterField(
            model_name='googlecalendar',
            name='file_path_doc',
            field=models.FileField(blank=True, null=True, upload_to=frontend.models.get_upload_path, verbose_name='google calendar credentials path'),
        ),
        migrations.AlterField(
            model_name='googlecalendardetail',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sites.site'),
        ),
    ]
