# Generated by Django 4.2 on 2024-09-20 07:10

from django.db import migrations, models
import frontend.models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0049_alter_googlecalendar_file_path_doc_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='googlecalendar',
            name='file_path_doc',
            field=models.FileField(default=None, upload_to=frontend.models.get_upload_path, verbose_name='google calendar credentials path'),
            preserve_default=False,
        ),
    ]
