# Generated by Django 4.2 on 2025-04-23 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0051_alter_googlecalendardetail_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='googlecalendardetail',
            name='cal_name',
            field=models.TextField(blank=True, null=True, verbose_name='calendar name'),
        ),
    ]
