# Generated by Django 4.2.20 on 2025-05-31 00:52

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0047_agencytranslation_payment_notes'),
        ('sites', '0002_alter_domain_unique'),
        ('frontend', '0053_logo_pos_alter_product_price_currency'),
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_initial_data', models.BooleanField(default=False)),
                ('is_need_refresh', models.BooleanField(default=False)),
                ('expired', models.DateTimeField()),
                ('model_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.modellist')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sites.site', verbose_name='site')),
            ],
            options={
                'verbose_name': 'log',
                'verbose_name_plural': 'logs',
            },
        ),
        migrations.CreateModel(
            name='AutoHeadline',
            fields=[
                ('id', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_initial_data', models.BooleanField(default=False)),
                ('title', models.CharField(max_length=300, verbose_name='title')),
                ('sub_title', models.CharField(blank=True, max_length=300, null=True, verbose_name='sub title')),
                ('slug', models.SlugField(blank=True, default='', editable=False, max_length=255, unique=True)),
                ('kind', models.SmallIntegerField(choices=[(1, 'News'), (2, 'Article'), (3, 'Announcement')], verbose_name='kind')),
                ('created_at', models.DateTimeField(editable=False)),
                ('categories', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='frontend.categories')),
            ],
            options={
                'verbose_name': 'auto headline',
                'verbose_name_plural': 'auto headlines',
            },
        ),
    ]
