# Generated by Django 4.2.20 on 2025-05-31 01:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('frontend', '0054_log_autoheadline'),
    ]

    operations = [
        migrations.AddField(
            model_name='autoheadline',
            name='admin',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='autoheadline',
            name='site',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='sites.site', verbose_name='site'),
            preserve_default=False,
        ),
    ]
