# Generated by Django 4.2.20 on 2025-05-31 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0055_autoheadline_admin_autoheadline_site'),
    ]

    operations = [
        migrations.AddField(
            model_name='autoheadline',
            name='is_editable',
            field=models.BooleanField(default=False),
        ),
    ]
