# Generated by Django 4.2.20 on 2025-06-02 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0056_autoheadline_is_editable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autoheadline',
            name='slug',
            field=models.SlugField(blank=True, default='', editable=False, max_length=255),
        ),
    ]
