# Generated by Django 4.2.22 on 2025-06-07 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0059_autopopular'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='is_editor_choice',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='article',
            name='is_editor_choice',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='news',
            name='is_editor_choice',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='socialmedia',
            name='kind',
            field=models.SmallIntegerField(choices=[(1, 'Facebook'), (2, 'Twitter'), (3, 'Pinterest'), (4, 'Youtube'), (5, 'Instagram'), (6, 'WhatsApp'), (7, 'TikTok')], verbose_name='kind'),
        ),
    ]
