# Generated by Django 4.2.22 on 2025-06-09 01:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sites', '0002_alter_domain_unique'),
        ('frontend', '0060_announcement_is_editor_choice_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='autoflashnews',
            name='created_at_str',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='autoheadline',
            name='created_at_str',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='autopopular',
            name='created_at_str',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.CreateModel(
            name='AutoRelatedNews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='title')),
                ('sub_title', models.CharField(blank=True, max_length=300, null=True, verbose_name='sub title')),
                ('slug', models.SlugField(blank=True, default='', editable=False, max_length=255)),
                ('kind', models.SmallIntegerField(choices=[(1, 'News'), (2, 'Article'), (3, 'Announcement')], verbose_name='kind')),
                ('is_editable', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(editable=False)),
                ('created_at_str', models.CharField(blank=True, max_length=30, null=True)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('categories', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='frontend.categories')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sites.site', verbose_name='site')),
            ],
            options={
                'verbose_name': 'auto related news',
                'verbose_name_plural': 'auto related news',
            },
        ),
        migrations.CreateModel(
            name='AutoArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='title')),
                ('sub_title', models.CharField(blank=True, max_length=300, null=True, verbose_name='sub title')),
                ('slug', models.SlugField(blank=True, default='', editable=False, max_length=255)),
                ('kind', models.SmallIntegerField(choices=[(1, 'News'), (2, 'Article'), (3, 'Announcement')], verbose_name='kind')),
                ('is_editable', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(editable=False)),
                ('created_at_str', models.CharField(blank=True, max_length=30, null=True)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('categories', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='frontend.categories')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sites.site', verbose_name='site')),
            ],
            options={
                'verbose_name': 'auto article',
                'verbose_name_plural': 'auto article',
            },
        ),
    ]
