# Generated by Django 4.2.22 on 2025-06-10 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0061_autoflashnews_created_at_str_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialmedia',
            name='kind',
            field=models.SmallIntegerField(choices=[(1, 'Facebook'), (2, 'Twitter'), (4, 'Youtube'), (5, 'Instagram'), (6, 'WhatsApp'), (7, 'TikTok')], verbose_name='kind'),
        ),
    ]
