# Generated by Django 4.2.22 on 2025-06-14 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0062_alter_socialmedia_kind'),
    ]

    operations = [
        migrations.AddField(
            model_name='autopopular',
            name='view_count',
            field=models.PositiveIntegerField(default=1, editable=False, verbose_name='view count'),
        ),
    ]
