# Generated by Django 4.2.22 on 2025-06-20 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0063_autopopular_view_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='position',
            field=models.PositiveIntegerField(choices=[(1, 'Top'), (2, 'Middle Top'), (3, 'Middle Bottom'), (4, 'Bottom')], default=1),
        ),
    ]
