# Generated by Django 4.2.22 on 2025-09-08 04:20

from django.db import migrations, models
import django.db.models.deletion
import django_ckeditor_5.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        ('frontend', '0066_autolistpage'),
    ]

    operations = [
        migrations.CreateModel(
            name='DirectUpdate',
            fields=[
                ('id', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_initial_data', models.BooleanField(default=False)),
                ('code', models.CharField(max_length=100, verbose_name='code')),
                ('value_type', models.SmallIntegerField(choices=[(1, 'Text'), (2, 'Icon'), (3, 'Image'), (4, 'UnorderList'), (5, 'Navigation')], verbose_name='value_type')),
                ('value_text', models.CharField(blank=True, max_length=300, null=True, verbose_name='text')),
                ('value_textarea', django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='value textarea')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sites.site')),
            ],
            options={
                'verbose_name': 'direct update',
                'verbose_name_plural': 'direct updates',
            },
        ),
    ]
