# Generated by Django 4.2.28 on 2026-02-23 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0067_directupdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='directupdate',
            name='value_type',
            field=models.SmallIntegerField(choices=[(1, 'text'), (2, 'icon'), (3, 'image'), (4, 'unordered-list'), (5, 'nav-bar')], verbose_name='value_type'),
        ),
    ]
