# Generated by Django 4.2.30 on 2026-05-11 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0068_alter_directupdate_value_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='position',
            field=models.PositiveIntegerField(choices=[(0, 'Default'), (1, 'Top'), (2, 'Middle Top'), (3, 'Middle Bottom'), (4, 'Bottom'), (5, 'Top Vertical')], default=0),
        ),
    ]
